[package]
name = "proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "proc_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = {version= "1.0", features = ["full"]}
quote = "1.0"
